/*
BASE DE DATOS:  
TRABAJO PRACTICO PAV1 - UTN-FRC
GRUPO 6
EMPRESA TU LUZ
*/
--CREATE DATABASE PROYECTO;
USE PROYECTO;

------------------------------------------------------------------------------
--TABLAS
------------------------------------------------------------------------------

--TABLA 1. PROVINCIAS
CREATE TABLE PROVINCIAS
(
PROVINCIA_ID   INT IDENTITY(1,1) PRIMARY KEY,
PROVINCIA_NOMBRE   VARCHAR(50) NOT NULL,
);

--TABLA 2. LOCALIDADES
CREATE TABLE LOCALIDADES
(
LOCALIDAD_ID   INT IDENTITY(1,1) PRIMARY KEY,
LOCALIDAD_NOMBRE	VARCHAR(50) NOT NULL,
PROVINCIA_ID	INT NOT NULL,
CONSTRAINT LOCALIDAD_PROV_FK FOREIGN KEY (PROVINCIA_ID) REFERENCES PROVINCIAS (PROVINCIA_ID)
);

--TABLA 3. BARRIOS
CREATE TABLE BARRIOS
(
BARRIO_ID   INT IDENTITY(1,1) PRIMARY KEY,
BARRIO_NOMBRE  VARCHAR(50) NOT NULL,
LOCALIDAD_ID   INT NOT NULL,
CONSTRAINT BARRIO_LOCA_FK FOREIGN KEY (LOCALIDAD_ID) REFERENCES LOCALIDADES (LOCALIDAD_ID)
);

--TABLA 4. TIPO DOCUMENTO

CREATE TABLE TIPOS_DOC
(
TIPO_DOC_ID INT IDENTITY(1,1) PRIMARY KEY,
TIPO_DOC_SIGLA VARCHAR(5) NOT NULL,
TIPO_DOC_NOMBRE   VARCHAR(50) NOT NULL
);

--TABLA 5. EMPLEADOS
CREATE TABLE EMPLEADOS
(
EMPLEADO_ID INT IDENTITY(1,1) PRIMARY KEY,
EMPLEADO_NUM_DOC  INT NOT NULL,	
TIPO_DOC_ID INT NOT NULL,
EMPLEADO_NOMBRE   VARCHAR(50) NOT NULL,
EMPLEADO_APELLIDO VARCHAR(50) NOT NULL,
DIRECCION   VARCHAR(50),
BARRIO_ID   INT,
TELEFONO VARCHAR(50),
EMPLEADO_ID_JEFE	INT,
EMPLEADO_ACTIVO   BIT,
CONSTRAINT EMPLEADO_TIPO_DOC_FK FOREIGN KEY (TIPO_DOC_ID) REFERENCES TIPOS_DOC (TIPO_DOC_ID),
CONSTRAINT EMPLEADO_BARR_FK FOREIGN KEY (BARRIO_ID) REFERENCES BARRIOS (BARRIO_ID),
CONSTRAINT EMPLEADO_JEFE_FK FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADOS (EMPLEADO_ID)
);

--TABLA 6. USUARIOS
CREATE TABLE USUARIOS
(
USUARIO_ID  INT IDENTITY(1,1) PRIMARY KEY,
USUARIO_NOMBRE VARCHAR(50) NOT NULL UNIQUE,
USUARIO_PASS   VARCHAR(50) NOT NULL,
EMPLEADO_ID INT,
USUARIO_ACTIVO BIT NOT NULL,
CONSTRAINT USUARIO_EMPL_FK FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADOS (EMPLEADO_ID)
);

--TABLA 7. CLIENTES
CREATE TABLE CLIENTES 
(
CLIENTE_ID  INT IDENTITY(1,1) PRIMARY KEY,
CLIENTE_CUIT   VARCHAR(50) NOT NULL UNIQUE,
CLIENTE_NOMBRE	VARCHAR(50) NOT NULL,
CLIENTE_APELLIDO	VARCHAR(50)	NOT NULL,
CLIENTE_ACTIVO	BIT NOT NULL
);

--TABLA 8. PROVEEDORES
CREATE TABLE PROVEEDORES
(
PROVEEDOR_ID   INT IDENTITY(1,1) PRIMARY KEY,
RAZON_SOCIAL   VARCHAR(50) NOT NULL,
MAIL  VARCHAR(50) UNIQUE,
TELEFONO VARCHAR(50),
PROVEEDOR_ACTIVO	BIT
);

--TABLA 9. PRODUCTOS
CREATE TABLE PRODUCTOS
(
PRODUCTO_ID INT IDENTITY(1,1) PRIMARY KEY,
PRODUCTO_NOMBRE   VARCHAR(50) NOT NULL,
PRODUCTO_DESCRIPCION VARCHAR(50),
PRODUCTO_PRECIO FLOAT,
CANTIDAD_STOCK INT NOT NULL,
PROVEEDOR_ID   INT NOT NULL,
PRODUCTO_ACTIVO BIT,
CONSTRAINT PRODUCTO_PROV_FK FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDORES (PROVEEDOR_ID)
);

-- TABLA 10. FORMAS DE PAGO
CREATE TABLE FORMAS_DE_PAGO
(
FORMA_DE_PAGO_ID INT IDENTITY(1,1) PRIMARY KEY,
FORMA_DE_PAGO_NOMBRE VARCHAR(50) NOT NULL
);

-- TABLA 11. VENTAS
CREATE TABLE VENTAS
(
VENTA_ID INT IDENTITY(1,1) PRIMARY KEY,
VENTA_FECHA DATETIME,
CLIENTE_ID  INT NOT NULL,
EMPLEADO_ID INT NOT NULL,
FORMA_DE_PAGO_ID INT NOT NULL,
--NUMERO_DE_FACTURA VARCHAR(50) NOT NULL,
CONSTRAINT VENTA_CLIE_FK FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (CLIENTE_ID),
CONSTRAINT VENTA_EMPL_FK FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADOS (EMPLEADO_ID),
CONSTRAINT VENTA_FORM_DE_PAGO_FK FOREIGN KEY (FORMA_DE_PAGO_ID) REFERENCES FORMAS_DE_PAGO (FORMA_DE_PAGO_ID)
);

-- TABLA 12. DETALLE DE VENTAS
CREATE TABLE DETALLE_VENTA
(
DETALLE_VENTA_ID  INT IDENTITY(1,1) PRIMARY KEY,
VENTA_ID INT NOT NULL,
PRODUCTO_ID INT NOT NULL,
CANTIDAD INT NOT NULL,
CONSTRAINT DETALLE_VENTA_VENT_FK FOREIGN KEY (VENTA_ID) REFERENCES VENTAS (VENTA_ID),
CONSTRAINT DETALLE_VENTA_PROD_FK FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS (PRODUCTO_ID)
);

-- TABLA 13. COTIZACIONES
CREATE TABLE COTIZACIONES
(
COTIZACION_ID  INT IDENTITY(1,1) PRIMARY KEY,
COTIZACION_FECHA DATETIME,
EMPLEADO_ID INT NOT NULL,
CONSTRAINT COTIZACION_EMPL_FK FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADOS (EMPLEADO_ID)
);

-- TABLA 14. DETALLE DE COTIZACION
CREATE TABLE DETALLE_COTIZACION
(
DETALLE_COTIZACION_ID   INT IDENTITY(1,1) PRIMARY KEY,
COTIZACION_ID  INT NOT NULL,
PRODUCTO_ID INT NOT NULL,
CANTIDAD INT NOT NULL,
CONSTRAINT DETALLE_COTIZACION_COTI_FK FOREIGN KEY (COTIZACION_ID) REFERENCES COTIZACIONES (COTIZACION_ID),
CONSTRAINT DETALLE_COTIZACION_PROD_FK FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS (PRODUCTO_ID)
);

------------------------------------------------------------------------------
--DATOS
------------------------------------------------------------------------------

--TABLA 1. PROVINCIAS
INSERT INTO PROVINCIAS (PROVINCIA_NOMBRE) VALUES ('Cordoba');
INSERT INTO PROVINCIAS (PROVINCIA_NOMBRE) VALUES ('Buenos Aires');
INSERT INTO PROVINCIAS (PROVINCIA_NOMBRE) VALUES ('Salta');

--TABLA 2. LOCALIDADES
INSERT INTO LOCALIDADES (LOCALIDAD_NOMBRE, PROVINCIA_ID) VALUES ('Localidad1',1);
INSERT INTO LOCALIDADES (LOCALIDAD_NOMBRE, PROVINCIA_ID) VALUES ('Localidad2',1);
INSERT INTO LOCALIDADES (LOCALIDAD_NOMBRE, PROVINCIA_ID) VALUES ('Localidad3',1);
INSERT INTO LOCALIDADES (LOCALIDAD_NOMBRE, PROVINCIA_ID) VALUES ('Localidad1',2);
INSERT INTO LOCALIDADES (LOCALIDAD_NOMBRE, PROVINCIA_ID) VALUES ('Localidad1',3);

--TABLA 3. BARRIOS
INSERT INTO BARRIOS (BARRIO_NOMBRE, LOCALIDAD_ID) VALUES ('Barrio1',1);
INSERT INTO BARRIOS (BARRIO_NOMBRE, LOCALIDAD_ID) VALUES ('Barrio2',1);
INSERT INTO BARRIOS (BARRIO_NOMBRE, LOCALIDAD_ID) VALUES ('Barrio3',1);
INSERT INTO BARRIOS (BARRIO_NOMBRE, LOCALIDAD_ID) VALUES ('Barrio1',2);
INSERT INTO BARRIOS (BARRIO_NOMBRE, LOCALIDAD_ID) VALUES ('Barrio1',3);
INSERT INTO BARRIOS (BARRIO_NOMBRE, LOCALIDAD_ID) VALUES ('Barrio1',4);
INSERT INTO BARRIOS (BARRIO_NOMBRE, LOCALIDAD_ID) VALUES ('Barrio1',5);

--TABLA 4. TIPO DOCUMENTO
INSERT INTO TIPOS_DOC (TIPO_DOC_SIGLA, TIPO_DOC_NOMBRE) VALUES ('DNI', 'Documento Nacional de Identidad');
INSERT INTO TIPOS_DOC (TIPO_DOC_SIGLA, TIPO_DOC_NOMBRE) VALUES ('PAS', 'Pasaporte');

--TABLA 5. EMPLEADOS
INSERT INTO EMPLEADOS (EMPLEADO_NUM_DOC, TIPO_DOC_ID, EMPLEADO_NOMBRE, EMPLEADO_APELLIDO, DIRECCION, BARRIO_ID, TELEFONO, EMPLEADO_ID_JEFE, EMPLEADO_ACTIVO) VALUES (12123465,1,'Cristian','Flores','Tandil 1000',1,'351264879',NULL,1);
INSERT INTO EMPLEADOS (EMPLEADO_NUM_DOC, TIPO_DOC_ID, EMPLEADO_NOMBRE, EMPLEADO_APELLIDO, DIRECCION, BARRIO_ID, TELEFONO, EMPLEADO_ID_JEFE, EMPLEADO_ACTIVO) VALUES (15646523,2,'Tom','Lopez','Ituzaingo 2000',1,'351123812',1,1);
INSERT INTO EMPLEADOS (EMPLEADO_NUM_DOC, TIPO_DOC_ID, EMPLEADO_NOMBRE, EMPLEADO_APELLIDO, DIRECCION, BARRIO_ID, TELEFONO, EMPLEADO_ID_JEFE, EMPLEADO_ACTIVO) VALUES (16764543,1,'Raul','Jimenez','Velez 230',2,'3516534812',1,1);


--TABLA 6. USUARIOS
INSERT INTO USUARIOS (USUARIO_NOMBRE, USUARIO_PASS, EMPLEADO_ID, USUARIO_ACTIVO) VALUES ('admi','admi',1,1);
INSERT INTO USUARIOS (USUARIO_NOMBRE, USUARIO_PASS, EMPLEADO_ID, USUARIO_ACTIVO) VALUES ('user','user',2,1);

--TABLA 7. CLIENTES
INSERT INTO CLIENTES (CLIENTE_CUIT, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_ACTIVO) VALUES ('A2345678910', 'Rodrigo', 'Calmalha',1);
INSERT INTO CLIENTES (CLIENTE_CUIT, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_ACTIVO) VALUES ('B2345S78910', 'Pedro', 'Salinas',1);
INSERT INTO CLIENTES (CLIENTE_CUIT, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_ACTIVO) VALUES ('C2345W78910', 'Myrella', 'Moncada',1);
INSERT INTO CLIENTES (CLIENTE_CUIT, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_ACTIVO) VALUES ('DD23W567890', 'Cindy', 'Jimenez',1);
INSERT INTO CLIENTES (CLIENTE_CUIT, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_ACTIVO) VALUES ('E2345678910', 'Rodrigo', 'Grados',1);
INSERT INTO CLIENTES (CLIENTE_CUIT, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_ACTIVO) VALUES ('F2345678910', 'Raul', 'Rodriguez',1);
INSERT INTO CLIENTES (CLIENTE_CUIT, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_ACTIVO) VALUES ('G2345678910', 'Jose', 'Lopez',1);
INSERT INTO CLIENTES (CLIENTE_CUIT, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_ACTIVO) VALUES ('H2345678910', 'Miguel', 'Martinez',1);
INSERT INTO CLIENTES (CLIENTE_CUIT, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_ACTIVO) VALUES ('I2345678910', 'Xiomara', 'Rodriguez',1);
INSERT INTO CLIENTES (CLIENTE_CUIT, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_ACTIVO) VALUES ('J2345678910', 'Agustina', 'Lopez',1);
INSERT INTO CLIENTES (CLIENTE_CUIT, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_ACTIVO) VALUES ('K2345678910', 'Lizet', 'Fernandez',1);
INSERT INTO CLIENTES (CLIENTE_CUIT, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_ACTIVO) VALUES ('L2345678910', 'Maria', 'Fernandez',1);
INSERT INTO CLIENTES (CLIENTE_CUIT, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_ACTIVO) VALUES ('M2345678910', 'Brigitte', 'Castillo',1);

--TABLA 8. PROVEEDORES
INSERT INTO PROVEEDORES (RAZON_SOCIAL, MAIL, TELEFONO, PROVEEDOR_ACTIVO) VALUES ('Luminarias S.A.','ventas@luminariasac.com','3514688795',1);
INSERT INTO PROVEEDORES (RAZON_SOCIAL, MAIL, TELEFONO, PROVEEDOR_ACTIVO) VALUES ('Foco S.A.','ventas@focosac.com','3598688795',1);

--TABLA 9. PRODUCTOS
INSERT INTO PRODUCTOS (PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_PRECIO, CANTIDAD_STOCK, PROVEEDOR_ID, PRODUCTO_ACTIVO) VALUES ('Luminaria Tubular Doble Blanca','Una luminaria',1200,16,1,1);
INSERT INTO PRODUCTOS (PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_PRECIO, CANTIDAD_STOCK, PROVEEDOR_ID, PRODUCTO_ACTIVO) VALUES ('Luminaria Tubular Doble Negra','Una luminaria',1400,8,1,1);
INSERT INTO PRODUCTOS (PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_PRECIO, CANTIDAD_STOCK, PROVEEDOR_ID, PRODUCTO_ACTIVO) VALUES ('Transformador','Componente electronico',100,9,2,1);
INSERT INTO PRODUCTOS (PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_PRECIO, CANTIDAD_STOCK, PROVEEDOR_ID, PRODUCTO_ACTIVO) VALUES ('Reactancia','Componente 1',100,13,2,0);
INSERT INTO PRODUCTOS (PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_PRECIO, CANTIDAD_STOCK, PROVEEDOR_ID, PRODUCTO_ACTIVO) VALUES ('Tubos de luz blanca x 1 m','Componente 2',100,23,2,1);
INSERT INTO PRODUCTOS (PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_PRECIO, CANTIDAD_STOCK, PROVEEDOR_ID, PRODUCTO_ACTIVO) VALUES ('Base cromo x 1m','Componente 3',100,21,1,1);

-- TABLA 10. FORMAS DE PAGO
INSERT INTO FORMAS_DE_PAGO (FORMA_DE_PAGO_NOMBRE) VALUES ('Efectivo');
INSERT INTO FORMAS_DE_PAGO (FORMA_DE_PAGO_NOMBRE) VALUES ('Tarjeta Debito');
INSERT INTO FORMAS_DE_PAGO (FORMA_DE_PAGO_NOMBRE) VALUES ('Tarjeta Credito');

-- TABLA 11. VENTAS
INSERT INTO VENTAS (VENTA_FECHA, CLIENTE_ID, EMPLEADO_ID, FORMA_DE_PAGO_ID) VALUES (GETDATE(), 1, 2, 1);    --1
INSERT INTO VENTAS (VENTA_FECHA, CLIENTE_ID, EMPLEADO_ID, FORMA_DE_PAGO_ID) VALUES (GETDATE(), 1, 2, 1);    --2
INSERT INTO VENTAS (VENTA_FECHA, CLIENTE_ID, EMPLEADO_ID, FORMA_DE_PAGO_ID) VALUES (GETDATE(), 1, 2, 1);    --3
INSERT INTO VENTAS (VENTA_FECHA, CLIENTE_ID, EMPLEADO_ID, FORMA_DE_PAGO_ID) VALUES (GETDATE(), 1, 2, 1);    --4
INSERT INTO VENTAS (VENTA_FECHA, CLIENTE_ID, EMPLEADO_ID, FORMA_DE_PAGO_ID) VALUES (GETDATE(), 1, 2, 1);    --5
INSERT INTO VENTAS (VENTA_FECHA, CLIENTE_ID, EMPLEADO_ID, FORMA_DE_PAGO_ID) VALUES (GETDATE(), 1, 2, 1);    --6

INSERT INTO VENTAS (VENTA_FECHA, CLIENTE_ID, EMPLEADO_ID, FORMA_DE_PAGO_ID) VALUES (GETDATE(), 1, 2, 1);    --7
INSERT INTO VENTAS (VENTA_FECHA, CLIENTE_ID, EMPLEADO_ID, FORMA_DE_PAGO_ID) VALUES (GETDATE(), 1, 2, 1);    --8
INSERT INTO VENTAS (VENTA_FECHA, CLIENTE_ID, EMPLEADO_ID, FORMA_DE_PAGO_ID) VALUES (GETDATE(), 1, 2, 1);    --9
INSERT INTO VENTAS (VENTA_FECHA, CLIENTE_ID, EMPLEADO_ID, FORMA_DE_PAGO_ID) VALUES (GETDATE(), 1, 2, 1);    --10
INSERT INTO VENTAS (VENTA_FECHA, CLIENTE_ID, EMPLEADO_ID, FORMA_DE_PAGO_ID) VALUES (GETDATE(), 1, 2, 1);    --11
INSERT INTO VENTAS (VENTA_FECHA, CLIENTE_ID, EMPLEADO_ID, FORMA_DE_PAGO_ID) VALUES (GETDATE(), 1, 2, 1);    --12

-- TABLA 12. DETALLE DE VENTAS
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 2, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 1, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 3, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 4, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 5, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 6, 4);

INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (2, 2, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (2, 1, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (2, 3, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (2, 4, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (2, 5, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (2, 6, 4);

INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (3, 2, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (3, 1, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (3, 3, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (3, 4, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (3, 5, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (3, 6, 4);

INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (4, 2, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (4, 1, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (4, 3, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (4, 4, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (4, 5, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (4, 6, 4);

INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (5, 2, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (5, 1, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (5, 3, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (5, 4, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (5, 5, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (5, 6, 4);

INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (6, 2, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (6, 1, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (6, 3, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (6, 4, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (6, 5, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (6, 6, 4);

INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (7, 2, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (7, 1, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (7, 3, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (7, 4, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (7, 5, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (7, 6, 4);

INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (8, 2, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (8, 1, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (8, 3, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (8, 4, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (8, 5, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (8, 6, 4);

INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (9, 2, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (9, 1, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (9, 3, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (9, 4, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (9, 5, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (9, 6, 4);

INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (10, 2, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (10, 1, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (10, 3, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (10, 3, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (10, 3, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (10, 3, 4);

INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (11, 1, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (11, 1, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (11, 1, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (11, 1, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (11, 1, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (11, 1, 4);

INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (12, 1, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (12, 2, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (12, 2, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (12, 2, 4);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (12, 2, 3);
INSERT INTO DETALLE_VENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD) VALUES (12, 2, 4);

-- TABLA 13. COTIZACIONES
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 1); --1
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 2); --2
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 3); --3
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 1); --4
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 1); --5
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 1); --6
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 1); --7
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 1); --8
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 2); --9
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 2); --10
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 2); --1
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 2); --2
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 2); --3
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 1); --4
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 1); --5
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 3); --6
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 3); --7
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 3); --8
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 3); --9
INSERT INTO COTIZACIONES (COTIZACION_FECHA, EMPLEADO_ID) VALUES (GETDATE(), 1); --10

-- TABLA 14. DETALLE DE COTIZACIONES
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 1, 3);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 3, 5);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 2, 4);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 4, 3);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 5, 5);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 6, 4);

INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (2, 1, 3);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (2, 3, 5);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (2, 2, 4);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (2, 4, 3);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (2, 5, 5);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (2, 6, 4);

INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (3, 1, 3);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (3, 3, 5);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (3, 2, 4);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (3, 4, 3);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (3, 5, 5);
INSERT INTO DETALLE_COTIZACION (COTIZACION_ID, PRODUCTO_ID, CANTIDAD) VALUES (3, 6, 4);

